services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: python_app
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - PYTHONPATH=/app:/app/website:/app/blogModel
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: >
      bash -c "
        echo 'Installing Python dependencies...' &&
        pip install --no-cache-dir --upgrade pip &&
        pip install --no-cache-dir -r requirements.txt &&
        echo 'Dependencies installed successfully!' &&
        pip install --no-cache-dir -r requirements-dev.txt &&
        echo 'Container is ready. You can now run: docker exec -it python_app bash' &&
        tail -f /dev/null
      "
