# Generated by Django 5.0.3 on 2024-04-08 20:46

import uuid

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("username", models.TextField(max_length=30, unique=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "author_url_slug",
                    models.TextField(default=uuid.uuid4, max_length=70, unique=True),
                ),
                (
                    "access_level",
                    models.IntegerField(
                        choices=[(1, "Author"), (2, "Reader")], default=1
                    ),
                ),
                ("history", models.TextField(blank=True, max_length=1000, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to=""
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Author",
            },
        ),
        migrations.CreateModel(
            name="Graduation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "graduation_level",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Graduado"),
                            (2, "Pós-graduado"),
                            (3, "Mestrado"),
                            (4, "Doutorado"),
                        ],
                        null=True,
                    ),
                ),
                ("course", models.TextField(blank=True, max_length=200, null=True)),
                ("school", models.TextField(blank=True, max_length=100, null=True)),
                ("year_graduation", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "concluded",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="website.author"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="graduations",
            field=models.ManyToManyField(
                blank=True, db_column="pk", related_name="+", to="website.graduation"
            ),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "month_begin",
                    models.IntegerField(
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        default=1,
                    ),
                ),
                ("year_begin", models.PositiveIntegerField()),
                (
                    "month_end",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        null=True,
                    ),
                ),
                ("year_end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "current_job",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "roles_description",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="website.author"
                    ),
                ),
            ],
            options={
                "db_table": "Job",
            },
        ),
        migrations.AddField(
            model_name="author",
            name="jobs",
            field=models.ManyToManyField(
                blank=True, db_column="pk", related_name="+", to="website.job"
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "url_slug",
                    models.TextField(default=uuid.uuid4, max_length=70, unique=True),
                ),
                ("text", models.TextField()),
                ("published_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="website.author"
                    ),
                ),
            ],
            options={
                "db_table": "Post",
            },
        ),
        migrations.AddField(
            model_name="author",
            name="written_posts",
            field=models.ManyToManyField(
                blank=True, db_column="pk", related_name="+", to="website.post"
            ),
        ),
        migrations.CreateModel(
            name="Reader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reader_name", models.CharField(blank=True, max_length=45, null=True)),
                ("access_level", models.IntegerField(default=2)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to=""
                    ),
                ),
                (
                    "saved_posts",
                    models.ManyToManyField(
                        blank=True, db_column="pk", to="website.post"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Reader",
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_media",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Facebook"),
                            (2, "Instagram"),
                            (3, "LinkedIn"),
                            (4, "X"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "social_media_profile",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user_social_media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.author"
                    ),
                ),
            ],
            options={
                "db_table": "Social_Media",
            },
        ),
        migrations.AddField(
            model_name="author",
            name="social_media",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="website.socialmedia"
            ),
        ),
    ]
