# Generated by Django 5.2.11 on 2026-05-26 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="graduation",
            options={"ordering": ["-graduation_level", "-year_graduation"]},
        ),
        migrations.AddField(
            model_name="reader",
            name="reader_name",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
        migrations.AlterField(
            model_name="reader",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="social_media",
            field=models.IntegerField(
                choices=[
                    (1, "Facebook"),
                    (2, "Instagram"),
                    (3, "LinkedIn"),
                    (4, "X"),
                    (5, "GitHub"),
                ]
            ),
        ),
    ]
