# Generated by Django 5.0.3 on 2025-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="SEO meta description (max 160 characters)",
                max_length=160,
                null=True,
            ),
        ),
    ]
