# Generated by Django 5.0.3 on 2024-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_job_year_begin_alter_job_year_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='year_begin',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='year_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
