# Generated by Django 5.2.11 on 2026-05-27 23:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_reader_reader_name_and_related_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="post",
            name="loves",
            field=models.ManyToManyField(blank=True, related_name="loved_posts", to=settings.AUTH_USER_MODEL),
        ),
    ]
