# Generated by Django 5.0.3 on 2024-03-18 22:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_job_year_begin_alter_job_year_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='current_job',
        ),
        migrations.AddField(
            model_name='author',
            name='author_url_slug',
            field=models.TextField(default=uuid.uuid4, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='jobs',
            field=models.ManyToManyField(blank=True, db_column='pk', related_name='+', to='website.job'),
        ),
        migrations.AlterField(
            model_name='author',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Author'), (2, 'Reader')], default=1),
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_level', models.IntegerField(blank=True, choices=[(1, 'Graduado'), (2, 'Pós-graduado'), (3, 'Mestrado'), (4, 'Doutorado')], null=True)),
                ('course', models.TextField(blank=True, max_length=200, null=True)),
                ('school', models.TextField(blank=True, max_length=100, null=True)),
                ('year_graduation', models.PositiveIntegerField(blank=True, null=True)),
                ('concluded', models.BooleanField(blank=True, default=False, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='graduations',
            field=models.ManyToManyField(blank=True, db_column='pk', related_name='+', to='website.graduation'),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.IntegerField(blank=True, choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'LinkedIn'), (4, 'X')], null=True)),
                ('social_media_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('user_social_media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.author')),
            ],
            options={
                'db_table': 'Social_Media',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='social_media',
            field=models.ManyToManyField(blank=True, related_name='+', to='website.socialmedia'),
        ),
    ]
