# Generated by Django 5.2.11 on 2026-06-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_post_cover_image_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-start_date", "-pk"]},
        ),
    ]
