# Generated by Django 5.0.3 on 2024-03-18 22:23

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("website", "Author")
    for row in MyModel.objects.all():
        row.author_url_slug = uuid.uuid4()
        row.save(update_fields=["author_url_slug"])

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_author_current_job_author_author_url_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
