# Generated by Django 5.0.3 on 2025-09-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_post_likes_post_loves"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="website.author",
            ),
        ),
    ]
