# Generated by Django 5.0.3 on 2024-03-18 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20240318_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_url_slug',
            field=models.TextField(default=uuid.uuid4, max_length=70, unique=True),
        ),
    ]
