# Generated by Django 5.0.3 on 2024-03-25 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20240318_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='user_social_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.author'),
        ),
    ]
