# Generated by Django 5.2.11 on 2026-06-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_sync_tag_icons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="icon",
            field=models.CharField(
                blank=True, help_text="Caminho relativo em static/, ex.: img/icons/tags/docker.svg", max_length=120
            ),
        ),
    ]
