# Generated by Django 5.2.11 on 2026-06-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_sitemapentry_sitemaphealthcheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="reader",
            name="author_upgrade_invited",
            field=models.BooleanField(
                default=False,
                help_text="Quando ativo, o leitor pode solicitar upgrade para autor.",
                verbose_name="Convite para perfil de autor",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Data de término"),
        ),
        migrations.AlterField(
            model_name="job",
            name="start_date",
            field=models.DateField(verbose_name="Data de início"),
        ),
    ]
