"""Catálogo de tags pré-definidas com ícones em static/."""

TAG_DEFINITIONS = [
    ("aws", "AWS", "img/icons/tags/aws.svg"),
    ("debian", "Debian", "img/icons/tags/debian.svg"),
    ("django", "Django", "img/icons/tags/django.svg"),
    ("docker", "Docker", "img/icons/tags/docker.svg"),
    ("fastapi", "FastAPI", "img/icons/tags/fastapi.svg"),
    ("fedora", "Fedora", "img/icons/tags/fedora.svg"),
    ("flask", "Flask", "img/icons/tags/flask.svg"),
    ("git", "Git", "img/icons/tags/git.svg"),
    ("githubactions", "GitHub Actions", "img/icons/tags/githubactions.svg"),
    ("go", "Go", "img/icons/tags/go.svg"),
    ("google-analytics", "Google Analytics", "img/icons/tags/google-analytics.svg"),
    ("google-app-script", "Google Apps Script", "img/icons/tags/google-app-script.svg"),
    ("google-search-console", "Google Search Console", "img/icons/tags/google-search-console.svg"),
    ("googlecloud", "Google Cloud", "img/icons/tags/googlecloud.svg"),
    ("googlecolab", "Google Colab", "img/icons/tags/googlecolab.svg"),
    ("google-sheets", "Google Sheets", "img/icons/tags/google-sheets.svg"),
    ("hyperv", "Hyper-V", "img/icons/tags/hyperv.svg"),
    ("java", "Java", "img/icons/tags/java.svg"),
    ("javascript", "JavaScript", "img/icons/tags/javascript.svg"),
    ("json", "JSON", "img/icons/tags/json.svg"),
    ("kubernetes", "Kubernetes", "img/icons/tags/kubernetes.svg"),
    ("linux", "Linux", "img/icons/tags/linux.svg"),
    ("matplotlib", "Matplotlib", "img/icons/tags/matplotlib.svg"),
    ("mongodb", "MongoDB", "img/icons/tags/mongodb.svg"),
    ("mysql", "MySQL", "img/icons/tags/mysql.svg"),
    ("nodejs", "Node.js", "img/icons/tags/nodejs.svg"),
    ("php", "PHP", "img/icons/tags/php.svg"),
    ("postgresql", "PostgreSQL", "img/icons/tags/postgresql.svg"),
    ("postman", "Postman", "img/icons/tags/postman.svg"),
    ("powershell", "PowerShell", "img/icons/tags/powershell.svg"),
    ("python", "Python", "img/icons/tags/python.svg"),
    ("react", "React", "img/icons/tags/react.svg"),
    ("redhat", "Red Hat", "img/icons/tags/redhat.svg"),
    ("seo", "SEO", "img/icons/tags/seo.svg"),
    ("spring", "Spring", "img/icons/tags/spring.svg"),
    ("swagger", "Swagger", "img/icons/tags/swagger.svg"),
    ("terraform", "Terraform", "img/icons/tags/terraform.svg"),
    ("ubuntu", "Ubuntu", "img/icons/tags/ubuntu.svg"),
    ("vagrant", "Vagrant", "img/icons/tags/vagrant.svg"),
    ("wordpress", "WordPress", "img/icons/tags/wordpress.svg"),
    ("xml", "XML", "img/icons/tags/xml.svg"),
    ("yaml", "YAML", "img/icons/tags/yaml.svg"),
]
